"""Add visibility to FeedPost

Revision ID: 417059ef636b
Revises: 86f912c10e46
Create Date: 2025-05-13 01:29:44.768885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417059ef636b'
down_revision = '86f912c10e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_post', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
