"""Add calorie_goal to MacroPost

Revision ID: 86f912c10e46
Revises: 96feb55c74c3
Create Date: 2025-05-12 20:28:51.850580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f912c10e46'
down_revision = '96feb55c74c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_goal', sa.String(length=10), server_default='maintain', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_post', schema=None) as batch_op:
        batch_op.drop_column('calorie_goal')

    # ### end Alembic commands ###
