"""Add macro fields to feed_post table

Revision ID: 8a106bde466b
Revises: 2432be22f743
Create Date: 2025-05-08 01:50:06.764341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a106bde466b'
down_revision = '2432be22f743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bmr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tdee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_post', schema=None) as batch_op:
        batch_op.drop_column('tdee')
        batch_op.drop_column('bmr')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
