"""Add calorie_goal to MacroPost

Revision ID: 96feb55c74c3
Revises: 1dde93afcc3d
Create Date: 2025-05-12 20:25:55.256193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96feb55c74c3'
down_revision = '1dde93afcc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_friend')
    with op.batch_alter_table('macro_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_goal', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_post', schema=None) as batch_op:
        batch_op.drop_column('calorie_goal')

    op.create_table('add_friend',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
